Sys.which("make")
install.packages("xlsx")
install.packages("readxl")
install.packages("dplyr")
library("xlsx")
library("readxl")
library("dplyr")
my_data <- read_excel("QPEDataClean.xlsx")
str(my_data)
